<?php

use Faker\Generator as Faker;
use Illuminate\Support\Carbon;

$factory->define(App\HistoricalFinancial::class, function (Faker $faker) {
    return [
        'listing_id' => function () {
            return factory('App\Listing')->states('override')->create()->id;
        },
        'year' => null,
        'number_transactions' => $faker->randomNumber(),
        'number_customers' => $faker->randomNumber(),
        'employee_wages_benefits' => $faker->randomNumber(),
        'employee_education_training' => $faker->randomNumber(),
        'contractor_expenses' => $faker->randomNumber(),
        'utilities' => $faker->randomNumber(),
        'rent_lease_expenses' => $faker->randomNumber(),
        'office_supplies' => $faker->randomNumber(),
        'cost_goods_sold' => $faker->randomNumber(),
        'transportation' => $faker->randomNumber(),
        'meals_entertainment' => $faker->randomNumber(),
        'travel_expenses' => $faker->randomNumber(),
        'professional_services' => $faker->randomNumber(),
        'interest_expense' => $faker->randomNumber(),
        'depreciation' => $faker->randomNumber(),
        'amortization' => $faker->randomNumber(),
        'general_operational_expenses' => $faker->randomNumber(),
        'business_taxes' => $faker->randomNumber(),
        'capital_expenditures' => $faker->randomNumber(),
        'stock_based_compensation' => $faker->randomNumber(),
        'change_working_capital' => $faker->randomNumber(),
        'cash_equivalents' => $faker->randomNumber(),
        'investments' => $faker->randomNumber(),
        'accounts_receivable' => $faker->randomNumber(),
        'inventory' => $faker->randomNumber(),
        'prepaid_expenses' => $faker->randomNumber(),
        'other_current_assets' => $faker->randomNumber(),
        'property_plant_equipment' => $faker->randomNumber(),
        'goodwill' => $faker->randomNumber(),
        'intangible_assets' => $faker->randomNumber(),
        'other_assets' => $faker->randomNumber(),
        'accounts_payable' => $faker->randomNumber(),
        'current_debt' => $faker->randomNumber(),
        'accrued_liabilities' => $faker->randomNumber(),
        'unearned_revenues' => $faker->randomNumber(),
        'other_current_liabilities' => $faker->randomNumber(),
        'long_term_debt' => $faker->randomNumber(),
        'deferred_income_taxes' => $faker->randomNumber(),
        'deferred_rent_expense' => $faker->randomNumber(),
        'other_liabilities' => $faker->randomNumber(),
        'paid_in_capital' => $faker->randomNumber(),
        'retained_earnings' => $faker->randomNumber(),
        'other_equity_accounts' => $faker->randomNumber(),
    ];
});

$factory->state(App\HistoricalFinancial::class, 'current_year', function ($faker) {
    return [
        'year' => Carbon::now(),
    ];
});

$factory->state(App\HistoricalFinancial::class, 'lcs-empty', function ($faker) {
    return [
        'listing_id' => function () {
            return factory('App\Listing')->states('lcs-empty')->create()->id;
        },
        'year' => null,
        'employee_wages_benefits' => null,
        'employee_education_training' => null,
        'contractor_expenses' => null,
        'utilities' => null,
        'rent_lease_expenses' => null,
        'office_supplies' => null,
        'cost_goods_sold' => null,
        'transportation' => null,
        'meals_entertainment' => null,
        'travel_expenses' => null,
        'professional_services' => null,
        'interest_expense' => null,
        'depreciation' => null,
        'amortization' => null,
        'general_operational_expenses' => null,
        'business_taxes' => null,
        'capital_expenditures' => null,
        'stock_based_compensation' => null,
        'change_working_capital' => null,
        'cash_equivalents' => null,
        'investments' => null,
        'accounts_receivable' => null,
        'inventory' => null,
        'prepaid_expenses' => null,
        'other_current_assets' => null,
        'property_plant_equipment' => null,
        'goodwill' => null,
        'intangible_assets' => null,
        'other_assets' => null,
        'accounts_payable' => null,
        'current_debt' => null,
        'accrued_liabilities' => null,
        'unearned_revenues' => null,
        'other_current_liabilities' => null,
        'long_term_debt' => null,
        'deferred_income_taxes' => null,
        'deferred_rent_expense' => null,
        'other_liabilities' => null,
        'paid_in_capital' => null,
        'retained_earnings' => null,
        'other_equity_accounts' => null,
    ];
});

$factory->state(App\HistoricalFinancial::class, 'lcs-full', function ($faker) {
    return [
        'listing_id' => function () {
            return factory('App\Listing')->states('lcs-full')->create()->id;
        },
        'year' => null,
        'employee_wages_benefits' => $faker->randomNumber(),
        'employee_education_training' => $faker->randomNumber(),
        'contractor_expenses' => $faker->randomNumber(),
        'utilities' => $faker->randomNumber(),
        'rent_lease_expenses' => $faker->randomNumber(),
        'office_supplies' => $faker->randomNumber(),
        'cost_goods_sold' => $faker->randomNumber(),
        'transportation' => $faker->randomNumber(),
        'meals_entertainment' => $faker->randomNumber(),
        'travel_expenses' => $faker->randomNumber(),
        'professional_services' => $faker->randomNumber(),
        'interest_expense' => $faker->randomNumber(),
        'depreciation' => $faker->randomNumber(),
        'amortization' => $faker->randomNumber(),
        'general_operational_expenses' => $faker->randomNumber(),
        'business_taxes' => $faker->randomNumber(),
        'capital_expenditures' => $faker->randomNumber(),
        'stock_based_compensation' => $faker->randomNumber(),
        'change_working_capital' => $faker->randomNumber(),
        'cash_equivalents' => $faker->randomNumber(),
        'investments' => $faker->randomNumber(),
        'accounts_receivable' => $faker->randomNumber(),
        'inventory' => $faker->randomNumber(),
        'prepaid_expenses' => $faker->randomNumber(),
        'other_current_assets' => $faker->randomNumber(),
        'property_plant_equipment' => $faker->randomNumber(),
        'goodwill' => $faker->randomNumber(),
        'intangible_assets' => $faker->randomNumber(),
        'other_assets' => $faker->randomNumber(),
        'accounts_payable' => $faker->randomNumber(),
        'current_debt' => $faker->randomNumber(),
        'accrued_liabilities' => $faker->randomNumber(),
        'unearned_revenues' => $faker->randomNumber(),
        'other_current_liabilities' => $faker->randomNumber(),
        'long_term_debt' => $faker->randomNumber(),
        'deferred_income_taxes' => $faker->randomNumber(),
        'deferred_rent_expense' => $faker->randomNumber(),
        'other_liabilities' => $faker->randomNumber(),
        'paid_in_capital' => $faker->randomNumber(),
        'retained_earnings' => $faker->randomNumber(),
        'other_equity_accounts' => $faker->randomNumber(),
    ];
});

$factory->state(App\HistoricalFinancial::class, 'lcs-hsf-zero', function ($faker) {
    return [
        'listing_id' => function () {
            return factory('App\Listing')->states('lcs-hsf-zero')->create()->id;
        },
        'year' => null,
        'employee_wages_benefits' => 0,
        'employee_education_training' => 0,
        'contractor_expenses' => 0,
        'utilities' => 0,
        'rent_lease_expenses' => 0,
        'office_supplies' => 0,
        'cost_goods_sold' => 0,
        'transportation' => 0,
        'meals_entertainment' => 0,
        'travel_expenses' => 0,
        'professional_services' => 0,
        'interest_expense' => 0,
        'depreciation' => 0,
        'amortization' => 0,
        'general_operational_expenses' => 0,
        'business_taxes' => 0,
        'capital_expenditures' => 0,
        'stock_based_compensation' => 0,
        'change_working_capital' => 0,
        'cash_equivalents' => 0,
        'investments' => 0,
        'accounts_receivable' => 0,
        'inventory' => 0,
        'prepaid_expenses' => 0,
        'other_current_assets' => 0,
        'property_plant_equipment' => 0,
        'goodwill' => 0,
        'intangible_assets' => 0,
        'other_assets' => 0,
        'accounts_payable' => 0,
        'current_debt' => 0,
        'accrued_liabilities' => 0,
        'unearned_revenues' => 0,
        'other_current_liabilities' => 0,
        'long_term_debt' => 0,
        'deferred_income_taxes' => 0,
        'deferred_rent_expense' => 0,
        'other_liabilities' => 0,
        'paid_in_capital' => 0,
        'retained_earnings' => 0,
        'other_equity_accounts' => 0,
    ];
});
