<template>
    <app-form-accordion
    header-title="Financial Details"
    class="listing-details-financial-details">

        <div slot="content">
            <!-- Revenue -->
            <input-textual
            type="price"
            name="revenue"
            :value="listing.revenue"
            placeholder="$ Amount"
            label="Revenue"
            wrap-class="input-half is-left"
            tooltip="Total annual sales for the business."></input-textual>

            <!-- EBITDA -->
            <input-textual
            type="price"
            name="ebitda"
            :value="listing.ebitda"
            placeholder="$ Amount"
            label="EBITDA"
            wrap-class="input-half is-right"
            tooltip="Earnings Before Interest, Tax, Depreciation, and Amortization."></input-textual>

            <!-- Pre-Tax Earnings -->
            <input-textual
            type="price"
            name="pre_tax_earnings"
            :value="listing.pre_tax_earnings"
            placeholder="$ Amount"
            label="Pre-Tax Earnings"
            wrap-class="input-half is-left"
            tooltip="Total income of the business before income taxes."></input-textual>

            <!-- Discretionary Cash Flow -->
            <input-textual
            type="price"
            name="discretionary_cash_flow"
            :value="listing.discretionary_cash_flow"
            placeholder="$ Amount"
            label="Discretionary Cash Flow"
            wrap-class="input-half is-right"
            tooltip="Total amount of operating free cash flow generated by the business.
            Reflects earnings before interest and non-cash expenses minus any required investments in capital
            expenditures or working capital."></input-textual>

            <!-- Real Estate -->
            <input-select
            label="Real Estate"
            name="real_estate_included"
            v-model="reIncluded"
            :options="financialDetailOptions"
            placeholder="Make Selection"
            wrap-class="input-half is-left"
            tooltip="Any real estate owned by the business, i.e. a building or land.  If there are no owned assets in this category (for example, the building is leased), select 'Not Applicable'."></input-select>

            <!-- Real Estate Estimated -->
            <input-textual
            type="price"
            name="real_estate_estimated"
            v-model="reEstimated"
            :input-disabled="reNotAvailable"
            :placeholder="reEstimatedPlaceholder"
            wrap-class="input-half is-right"></input-textual>

            <input-textual
            type="textarea"
            name="real_estate_description"
            :value="listing.real_estate_description"
            :input-disabled="reNotAvailable"
            :placeholder="reDescriptionPlaceholder"></input-textual>

            <!-- Fixtures Equipment Included -->
            <input-select
            label="Fixtures Equipment"
            name="fixtures_equipment_included"
            v-model="feIncluded"
            :options="financialDetailOptions"
            placeholder="Make Selection"
            wrap-class="input-half is-left"
            tooltip="Physical assets owned by the business, i.e. kitchen equipment, trucks, etc."></input-select>

            <!-- Fixtures Equipment Estimated -->
            <input-textual
            type="price"
            name="fixtures_equipment_estimated"
            v-model="feEstimated"
            :placeholder="feEstimatedPlaceholder"
            :input-disabled="feNotAvailable"
            wrap-class="input-half is-right"></input-textual>

            <input-textual
            type="textarea"
            name="fixtures_equipment_description"
            :value="listing.fixtures_equipment_description"
            :input-disabled="feNotAvailable"
            :placeholder="feDescriptionPlaceholder"></input-textual>

            <!-- Inventory Included -->
            <input-select
            label="Inventory"
            name="inventory_included"
            v-model="invIncluded"
            :options="financialDetailOptions"
            placeholder="Make Selection"
            wrap-class="input-half is-left"
            tooltip="Any products or merchandise owned by the business, i.e. raw ingredients,
            finished products for sale, etc."></input-select>

            <!-- Inventory Estimated -->
            <input-textual
            type="price"
            name="inventory_estimated"
            v-model="invEstimated"
            :placeholder="invEstimatedPlaceholder"
            :input-disabled="invNotAvailable"
            wrap-class="input-half is-right"></input-textual>

            <!--Inventory Description-->
            <input-textual
            type="textarea"
            name="inventory_description"
            :value="listing.inventory_description"
            :input-disabled="invNotAvailable"
            :placeholder="invDescriptionPlaceholder"></input-textual>
        </div>
    </app-form-accordion>
</template>

<script>
module.exports = {
    props: {
        dataListing: {
            type: Object,
            required: true
        },

        financialDetailOptions: {
            type: Array,
            required: true
        },

        formId: {
            type: String,
            default: ""
        },

        percentageComplete: {
            type: Number,
            default: 0
        }
    },

    data() {
        return {
            listing: this.dataListing,
            reEstimatedPlaceholder: "Estimated Value",
            reDescriptionPlaceholder: "Description",
            reIncluded: this.dataListing.real_estate_included,
            reEstimated: this.dataListing.real_estate_estimated,
            reNotAvailable: this.notAvailable(
                this.dataListing.real_estate_included
            ),
            feEstimatedPlaceholder: "Estimated Value",
            feDescriptionPlaceholder: "Description",
            feIncluded: this.dataListing.fixtures_equipment_included,
            feEstimated: this.dataListing.fixtures_equipment_estimated,
            feNotAvailable: this.notAvailable(
                this.dataListing.fixtures_equipment_included
            ),
            invEstimatedPlaceholder: "Estimated Value",
            invDescriptionPlaceholder: "Description",
            invIncluded: this.dataListing.inventory_included,
            invEstimated: this.dataListing.inventory_estimated,
            invNotAvailable: this.notAvailable(
                this.dataListing.inventory_included
            )
        };
    },

    methods: {
        notAvailable(value) {
            let included = parseInt(value, 10);

            return isNaN(included) || included <= 1;
        },

        naPlaceholder(value) {
            let included = parseInt(value, 10);

            return value === 1 ? "N/A" : "Estimated Value";
        },

        naDescPlaceholder(value) {
            let included = parseInt(value, 10);

            return value === 1 ? "N/A" : "Description";
        }
    },

    watch: {
        reIncluded(value) {
            this.reNotAvailable = this.notAvailable(value);
            this.reEstimatedPlaceholder = this.naPlaceholder(this.reIncluded);
            this.reDescriptionPlaceholder = this.naDescPlaceholder(
                this.reIncluded
            );

            if (this.reNotAvailable) {
                this.reEstimated = "";
                this.listing.real_estate_description = "";
            }
        },

        feIncluded(value) {
            this.feNotAvailable = this.notAvailable(value);
            this.feEstimatedPlaceholder = this.naPlaceholder(this.feIncluded);
            this.feDescriptionPlaceholder = this.naDescPlaceholder(
                this.feIncluded
            );

            if (this.feNotAvailable) {
                this.feEstimated = "";
                this.listing.fixtures_equipment_description = "";
            }
        },

        invIncluded(value) {
            this.invNotAvailable = this.notAvailable(value);
            this.invEstimatedPlaceholder = this.naPlaceholder(this.invIncluded);
            this.invDescriptionPlaceholder = this.naDescPlaceholder(
                this.invIncluded
            );

            if (this.invNotAvailable) {
                this.invEstimated = "";
                this.listing.inventory_description = "";
            }
        }
    },

    mounted() {
        this.reEstimatedPlaceholder = this.naPlaceholder(this.reIncluded);
        this.reDescriptionPlaceholder = this.naDescPlaceholder(this.reIncluded);

        this.feEstimatedPlaceholder = this.naPlaceholder(this.feIncluded);
        this.feDescriptionPlaceholder = this.naDescPlaceholder(this.feIncluded);

        this.invEstimatedPlaceholder = this.naPlaceholder(this.invIncluded);
        this.invDescriptionPlaceholder = this.naDescPlaceholder(
            this.invIncluded
        );
    }
};
</script>
